language: generic
sudo: required
serviced:
  - docker

before_install:
  - docker build -t paulh98/docker-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true paulh98/docker-udemy npm run test